import {
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Archive,
  ArrowDown,
  Activity,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AudioWaveform,
  Banknote,
  Bold,
  Book,
  BookKey,
  BookOpen,
  Bot,
  Boxes,
  BriefcaseConveyorBelt,
  Building2,
  Calendar,
  CalendarIcon,
  Car,
  CarFront,
  Check,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  CircleCheck,
  CircleHelp,
  ClipboardList,
  ClipboardPenLine,
  Command,
  Droplet,
  Dock,
  Eye,
  EyeOff,
  File,
  FileDigit,
  FileUser,
  FilePlus2,
  FileQuestion,
  FileWarning,
  Folder,
  Frown,
  Fuel,
  GalleryVerticalEnd,
  Gauge,
  Hammer,
  Hash,
  Handshake,
  Home,
  HousePlug,
  Hourglass,
  IdCard,
  Import,
  Inbox,
  Info,
  Italic,
  KeyRound,
  Link,
  Lightbulb,
  Link2,
  Layers2,
  List,
  ListOrdered,
  Lock,
  LockOpen,
  LogOut,
  Mail,
  MapPin,
  MapPinCheckInside,
  Menu,
  Container,
  Package,
  PaintBucket,
  Pause,
  Pencil,
  Phone,
  Tag,
  Plug2,
  Plus,
  ScrollText,
  Omega,
  Search,
  Send,
  ShieldQuestionMark,
  Settings,
  Factory,
  Settings2,
  ShoppingBag,
  SquareTerminal,
  Strikethrough,
  Trash2,
  Truck,
  Timer,
  Underline,
  User,
  Users,
  Wrench,
  X,
  Zap,
} from "lucide-react";

export const icons = {
  hourglass: Hourglass,
  activity: Activity,
  import: Import,
  search: Search,
  clipboardList: ClipboardList,
  filePlus: FilePlus2,
  handshake: Handshake,
  zap: Zap,
  briefcase: BriefcaseConveyorBelt,
  settings: Settings,
  lightbulb: Lightbulb,
  inbox: Inbox,
  calendarIcon: CalendarIcon,
  layers2: Layers2,
  gallery: GalleryVerticalEnd,
  factory: Factory,
  audio: AudioWaveform,
  dock: Dock,
  command: Command,
  square: SquareTerminal,
  bot: Bot,
  bookOpen: BookOpen,
  settings2: Settings2,
  logout: LogOut,
  tag: Tag,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strikethrough: Strikethrough,
  alignLeft: AlignLeft,
  alignCenter: AlignCenter,
  alignJustify: AlignJustify,
  alignRight: AlignRight,
  fileUser: FileUser,
  listOrdered: ListOrdered,
  lockOpen: LockOpen,
  lock: Lock,
  archive: Archive,
  circleCheck: CircleCheck,
  ShieldQuestionMark: ShieldQuestionMark,
  file: File,
  fileDigit: FileDigit,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  link: Link,
  pin: MapPin,
  bookKey: BookKey,
  container: Container,
  hash: Hash,
  email: Mail,
  link2: Link2,
  housePlug: HousePlug,
  clipboard: ClipboardPenLine,
  gas: Fuel,
  clean: Droplet,
  plug2: Plug2,
  gauge: Gauge,
  pinCheck: MapPinCheckInside,
  eye: Eye,
  Building2,
  eyeOff: EyeOff,
  key: KeyRound,
  plus: Plus,
  user: User,
  users: Users,
  arrowRight: ArrowRight,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  check: Check,
  pencil: Pencil,
  timer: Timer,
  home: Home,
  list: List,
  menu: Menu,
  x: X,
  trash: Trash2,
  calendar: Calendar,
  omega: Omega,
  boxes: Boxes,
  package: Package,
  shoppingBag: ShoppingBag,
  wrench: Wrench,
  truck: Truck,
  banknote: Banknote,
  fileQuestion: FileQuestion,
  fileWarning: FileWarning,
  phone: Phone,
  hammer: Hammer,
  frown: Frown,
  building: Building2,
  folder: Folder,
  idCard: IdCard,
  info: Info,
  book: Book,
  circleHelp: CircleHelp,
  car: Car,
  carFront: CarFront,
  paintBucket: PaintBucket,
  scrollText: ScrollText,
  chevronsUpDown: ChevronsUpDown,
  pause: Pause,
  send: Send,
};

export type IIcons = keyof typeof icons;
